services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: backend
    network_mode: host  # Use host network
    volumes:
      - ./backend:/app
    env_file: 
      - ./backend/.env 
    environment:
      - PORT=8000  # Ensure app binds to 8000 on host
    # No 'ports' needed (host mode exposes all ports)

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: frontend
    network_mode: host  # Use host network
    depends_on:
      - backend
    env_file: 
      - ./frontend/.env 
    environment:
      - PORT=3000  # Ensure app binds to 3000 on host
    # No 'expose' or 'ports' needed (host mode exposes all ports)

  nginx:
    image: nginx:alpine
    container_name: nginx
    network_mode: host  # Use host network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
